%%{init: {'flowchart': {'defaultRenderer': 'elk'}} }%%
graph TD
     basic_types["cl_basic_types"]
    subgraph "Core Dart Packages"
       
        store["store"]
        dart_client["cl_server_dart_client"]
        local_store["local_store"]
    end

    subgraph "Utility Flutter Packages"
        colan_widgets["colan_widgets"]
        
        
        
        form_factory["form_factory"]
        
    end

   
    services["colan_services"]

    subgraph "Applications"
        keep_it["keep_it"]
       %%  face_it["face_it_desktop"]
    end
    camera["cl_camera"]
    media_editors["media_editors"]
    entity_viewers["cl_entity_viewers"]
    media_tools["cl_media_tools"]
    date_picker["yet_another_date_picker"]


    %% Core Dependencies
    store --> basic_types
    dart_client --> basic_types
    dart_client --> store
    local_store --> basic_types
    local_store --> store

    %% Utility Dependencies
    media_tools --> basic_types
    form_factory --> basic_types
    form_factory --> colan_widgets

    %% Feature Dependencies
    entity_viewers --> basic_types
    entity_viewers --> media_tools
    entity_viewers --> colan_widgets
    entity_viewers --> date_picker

  
    
    
    %% colan_services Dependencies
    services --> basic_types
    services --> camera
    services --> entity_viewers
    services --> media_tools
    services --> dart_client
    services --> colan_widgets
    services --> form_factory
    services --> local_store
    services --> media_editors
    services --> store

   

    %% App Dependencies
    keep_it --> services
   

    %% face_it --> basic_types
    %% face_it --> services
    %% face_it --> colan_widgets
    %% face_it --> content_store
    %% face_it --> store

    linkStyle 2 stroke-width:0px;